name: Docker Image
on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]
  
jobs:
  
  build: 

     runs-on: ubuntu-latest
    
     steps: 
       - uses: actions/checkout@v3
       - name: Build the Docker Image
         run: docker build -t react .
       - name: Tag the Docker image
         run: docker tag react ramadevidyuthi2021/react1js
       - name: Docker login
         run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
       - name: docker push
         run: docker push ramadevidyuthi2021/react1js
